services:
  app:
    build: .
    environment:
      URL_DATA: jdbc:postgresql://postgres:5432/task_tracker
    ports:
      - "9090:8080"
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1024M'
        reservations:
          cpus: 0.5
          memory: '512M'


  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: task_tracker
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '1G'
        reservations:
          cpus: '0.5'
          memory: '512M'

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: hdnhdxv@gmail.com
      PGADMIN_DEFAULT_PASSWORD: adminRoot
    ports:
      - "16543:80"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '256M'
        reservations:
          cpus: '0.1'
          memory: '128M'

volumes:
  pgdata: